# Unit testing to replace Travis CI, runs existing pytest script. Based on PsychoPy's own CI test system.

name: pytest

on: [push, pull_request]

permissions:
  contents: read

jobs:
  testsuite_mac:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Pre-Install
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 xmlschema
        pip install wheel
        pip install six  # for configobj and wxpython
        pip install distro  # used by createInitFile
    - name: Install PsychoPy and dependencies
      run: |
        # for pocketsphinx we need this adapted package:
        brew install swig vlc
        # We need openal-soft, but the latest version breaks and brew is bad at versions
        brew tap-new $USER/local-openal-soft
        brew extract --version=1.21.1 openal-soft $USER/local-openal-soft
        brew search /openal-soft/ #backup in case the below line breaks
        brew install $USER/local-openal-soft/openal-soft@1.21.1
        # Trying to force the right version
        echo 'export PATH="/usr/local/opt/openal-soft@1.21.1/bin:$PATH"' >> /Users/runner/.bash_profile
        export LDFLAGS="-L/usr/local/opt/openal-soft@1.21.1/lib"
        export CPPFLAGS="-I/usr/local/opt/openal-soft@1.21.1/include"
        export CFLAGS="-I$(brew --cellar)/openal-soft/1.21.0/include/AL" 
        export LDFLAGS=-L"$(brew --cellar)/openal-soft/1.21.0/lib" 
        pip install git+https://github.com/Im-Fran/pocketsphinx-python
        pip install mock
        pip install psychopy
    - name: Test with Pytest
      run:
        pytest
